# Generated by Django 6.0.2 on 2026-04-18 13:41

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisme', '0002_page_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='表示名'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/', verbose_name='プロフィール画像'),
        ),
    ]
