# Generated by Django 6.0.2 on 2026-04-18 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisme', '0003_customuser_display_name_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedword',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='オーナー'),
        ),
    ]
