# Generated by Django 6.0.2 on 2026-04-19 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisme', '0004_searchedword_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='章タイトル')),
                ('content', models.TextField(blank=True, verbose_name='章の内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='wisme.page', verbose_name='所属メモ')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
