# Generated by Django 6.0.2 on 2026-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisme', '0005_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedword',
            name='word',
            field=models.CharField(db_index=True, max_length=100, verbose_name='意味を知りたい単語'),
        ),
    ]
