# Generated by Django 6.0.2 on 2026-05-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisme', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='プロフィール画像'),
        ),
    ]
